import java.io.IOException;

public class Main {

    public static void main(String[] args) throws IOException {
        Decoder decoder = new Decoder("ABCDEFGHIJKLMNOPQRSTUVWXYZ", 3);
        System.out.println("result");

//        for (int i = 0; i < 130; i++) {
        DecryptionResult result = decoder.decode("EFFPQLMEHEMVPCPYFLMVHQLUHYTCETHQEKLPVMMVHQLUWEOLFPQLIVDLWLULMVHQLUCYAUHUYDUEOSQY" +
                "ATFFVSMUVOVWEPLPQVSPCHLYGETDYUVPQOGUYOOYWYETHQEKLPVMYWLSASVWDEWCPLSPYGDYYFWLSSYGGVPCYAEULMYO" +
                "GYUPEKTLBVPQCYAOECASLVWFLRYGMYVWMVFLWMLNESVSNVLREOVWEPVYWSPEPVSPVMETPLSPSYUBQEPLILUOLPQYFCYAGLLT" +
                "BVTTSQYBPQLKLSPULSATPPUCPYPQVWNYGBQEPBVTTQEHHLWVGPQLNLCMYWPEVWSSEOLMQEUEMPLUSEPFVGGLULWPHYSVPVYWSB" +
                "VTTCYAUHUYDUEOSPVTTKLQEILMYUULMPTC");
        System.out.println(result);
        System.out.println();
        System.out.println();
//            System.out.println(i+". "+ result);
//    }
//        System.out.println("result = " + result);
        Decoder decoder2 = new VigenereDecoder("ABCDEFGHIJKLMNOPQRSTUVWXYZ", 3);
        DecryptionResult result2 = decoder2.decode("EDVRLESZMLARCTGBICANLEJYRYCGRDGDTODWELHFEBWRMCUGTHWPWTZCSNWSWEVGRTZCGI" +
                "HFIRLCBTKFIRWFESLUINLWWIPGRDWNINVCRTJYRDGKPYUFSSWLQOFMELHFEBWRMCKSFSLGXULGSNHYXTWPRSXMVESALLWRXEJDVOECR" +
                "GDGWHSJTHSZITARMSUJIAJRLALWSUUYRNGKSRWPILQMRTZCWAECWIENPEJMYTALIOXEYEKQMNYRLECCCBQCBHSSWTATISWYVCZULIUF" +
                "COMNVOTYFLQSWEVRSDWAMPZCVTZGWPSPEGJYTHOGPLLFIIFBIXGDGOALGIVCRCWQXIDJAOJIESSQYGYCWTAMRYGSGAFRVYLMHINGHEL" +
                "FIMWQWAYCMNHYVTKZCTZCRUEZIRGDGHSPECLCVSALEKWWENVYTPDWJRWOYEFACAFYPYKGWTGCECZMJTZCQCSLCOMDMNVYAAQRSUKCLI" +
                "YFIRGPHEJDVEISINUWWTSRMSLGGSOGXHLFMSLWTEGDGIHFIRLFINWVXPSPEGJYTHUMRTSGRSKMQEHPITLWMNLCVEKRMNYGRFGPQALGS" +
                "NSZSULQSMWYHDARMOFYPRWUERV");

        System.out.println(result2);

        Decoder decoder3 = new VigenereDecoder("ABCDEFGHIJKLMNOPQRSTUVWXYZ", 3);
        DecryptionResult result3 = decoder3.decode("UOWZWZTIDHMORKKLREROAESKWOELRVAPAIDNRAGKVFTYLZDOTXTENKFVNTRLUSTYH" +
                "KESTUPPTZRUOFJSLCIWLJLOTDAIOERMSODHWRIQHJARVIBLLPKPDDVQVNTYHAERILAORPRMUNZYLRSZWFASNHSLAJSVRTIDFALFIDHAK" +
                "HEACKOFTOCRVKFFUAHEWLYSTFQLWHFGLCRPSASTYHSASKSPECVDUDFZQKSTYHWRIQHJANKDREIKDSLAEGPSTYHUFRVHAODFZOATVYLRH" +
                "VZPSHVVAODFZPTHZWAHIJOHSTVQJRYGWLDTVAAISROTOSKWOEHRUKESKBVUCRQNETNLAHSZPWLEGRSYACSOABVWPCCZSOERJLAUTZOPZ" +
                "EJVVMEKHJHNZTBESKRKRIMHAHETUFPTRQHLYKLJAWRBMRODWOERZJOTDZULCTZRUMIJVWELCHKWOIGZMAEXHLLPFOANXHKCHRUHCTVUZ" +
                "BEWRYEEEFYYPKLVNMVDUINXOLSSTRTBIEDAIOEVVFLVWAERJLUCLLGLDBLWAHEGUVGRRPAODVFPPHVUAHIJWLXTRXAOMRWPCACOFWIKK" +
                "VUTYXTANYHSPWZOSRETHPVEKZVMOIHWOIEWZINJWLADFIVNEPRBMAPZHNTKRZEAIFOFOIDDAYKRBSEBQVWNGOHINKHETAKWHCKRVFOUT" +
                "DUGUVVZSODHDORUVVREMHUPHIDZESWUVMTYHSASKSHRAXUHPHGUVVIULUGTYHWROXUHMWZWOPOJVPBLVSSAIEWLXTGKYASVVKOEJQVTM" +
                "RNLITERAAUKRTATZF");

        System.out.println(result3);

        Decoder decoder4 = new VigenereDecoder("ABCDEFGHIJKLMNOPQRSTUVWXYZ",3);
        DecryptionResult result4 = decoder4.decode("LSSYEWRPLRFHZZFXHUZWMGUWVOSWKWFDWMRHZPPDVZVTBPAIEMSARWYSHNRBPZQCUSYC" +
                "CDARXWCXELAQSWGSJPROECEOHQRLELWWKSFEFJAQWWCXXLXZFGSZGHSAFLLZLCUSPWSOGLKTRNKCXIQUNGKYIVOSJIHFBCFPLOBIJIH" +
                "QRFWTGGNLDLFPRDGILFUWUSLWFLHLFCBXPKCVRLGWRGEIJYWCHFWIKRZVXZIAKTDZKNEDGEGGYCULHNQCFIHXCLGQLRGWLIOUFCZLGJ" +
                "FCEPLYNDWCLPYUWOLCBLARLOPCEIHQRFAGVCKGAOUGJVSELHBIPCFNKGWEFLUWFRTXELADWWKHZPPXKSMELDCLXCCWGHZPFRTPJHOUY" +
                "LXCCVKWFDWMRLZSSARGPLUFUWLPLLBZGCSMYSLESSNZDIMXHBWPRRFLAYGRQSPEVRFLDPHCRFPJWDKASJQXAQWLZGSFGXLNFSJJCMRL" +
                "OSOCJOKTBBJRWMICCZWLGNKRGIBXGTGCUNGLLZDXFHGYZRXSPEVNKGWNFNGLXZVAOMLPQXQSPKFRZHWYLMACFPLBVRWICOGVWIFNJOJ" +
                "OCWPSFZIGTSLIWCVHPXOHKQGXSGVBPSOCQMKZANKHAXSYYOLPFGNBVIHQVGADHQRLGYZHVYQIWLNBTPLBHFWHVXJOKEVNSWJDHXASLZ" +
                "UNGLLSWBKAWDGJTSPCWPUHBFGCUFAEWWTAWEVNCZSTBCRLLIRXRGFZHLBIFESDSSHELOBFLSOCKMGFLJESPQFNRHGOCFLOLPJNELQZI" +
                "GJWKSWDLCDIKWAHPQWWQOFJHQVBYIOCRVWIRNFWYYORRRPAZJPSPEVNASAEVNEMGFLJESPNCCFSSCQQVBYIKNFZJZUBBAWZBNKSDDSP" +
                "HPEUCTSHCWLRLXTFBGLHYSJFSPISJISLSSGRAAEMURHLTFDCLLSSARLKZSERFQZBNKKGFZMXBGHPOBFKFFNKHZPMPHSKDSMKHZTGXAS" +
                "PECXYOLPWOLCMCDABUJLAGQSUTDQRFWOHQVGSFHXZOLTQJYZQIHQRBPTLBUCMWRGPCFRFJGIDLHNJWLSLCUSELLRZOEDQXESPZBNPCM" +
                "WRGNQZTSERKAEVGGVADLUNPOZTTLCMCLFBFCIQJAADVSGNUJPOCKRWLZGNHPEHNKBWIIGCIRKZNKRSJOUBILEVRFLSIZRGHDILUNHWD" +
                "EQNBCJCDKL");
        System.out.println(result4);
    }
}